### ISSUE TITLE
Problema con los ejercicios borrados y los entregados por docentes

### ISSUE THREAD

**Issue by FrancoPrime** [reinvent-fiuba/RPL-2.0-web#126]
Los ejercicios borrados siguen apareciendo en envíos por alumno.
Cuando un docente prueba un ejercicio, aumenta la contador de **alumnos** exitosos, siendo que esos envios no quedan guardados ni figuran en otra parte.
![image](https://user-images.githubusercontent.com/21978872/118736613-600ba080-b819-11eb-90f8-10b97a6a1cbc.png)

**Comment by alelevinas** [comment]
@FrancoPrime  porfa cuando puedas confirmame que esto está solucionado o si seguís viendo el problema

**Comment by FrancoPrime** [comment]
Solucionados los dos problemas. Gracias.
