### ISSUE TITLE
Achicar botón de "Desinscribirse" y agregar una confirmación

### ISSUE THREAD

**Issue by alelevinas** [reinvent-fiuba/RPL-2.0-web#127]
La gente se equivoca, anyways está muy grande la verdad

![image](https://user-images.githubusercontent.com/12226623/119506172-93908280-bd65-11eb-9869-c7a937113898.png)

@manucamejo

**Comment by manucamejo** [comment]
Se cambio la visualización para que sea mas intuitiva y se agrego un paso extra de seguridad al desinscribirse de un curso.
![imagen](https://user-images.githubusercontent.com/20927859/119550422-c723da80-bd6e-11eb-8036-5b3980adb088.png)
![imagen](https://user-images.githubusercontent.com/20927859/119550481-d86ce700-bd6e-11eb-9344-d7719afa4c6b.png)
